### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by xiayizhan2017** [autonomousvision/occupancy_networks#17]
hello,
when I run the eval_meshes.py, it has same warning.
'warning: contains1 != contains2 for same points.'
I wonder if this warning will affect the results.

**Comment by xiayizhan2017** [comment]
Thanks you in advance!

**Comment by LMescheder** [comment]
Hi @xiayizhan2017,
our script for checking if a point is inside or outside the mesh checks the number of intersections with rays going in two different directions. If those two checks lead to different results, then the warning occurs. 
This either happens because the mesh is not watertight or if there are numerical instabilities. We tried to avoid the later case by writing our code in a [numerically stable fashion](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/libmesh/inside_mesh.py#L129), but it's difficult to completely resolve it. Nonetheless, these instabilities should only happen rarely and should not affect the overall results.

**Comment by xiayizhan2017** [comment]
Thanks!
