### ISSUE TITLE
Noise level added to point clouds

### ISSUE THREAD

**Issue by MiZhenxing** [autonomousvision/occupancy_networks#18]
Hello, thanks for your code and data. 
As described in paper, you "apply noise using a Gaussian distribution with zero mean and standard deviation 0.05 to the point clouds." However, I found in the  configs/pointcloud/onet.yaml that the pointcloud_noise is set as 0.005. So I am wondering which noise level you used in your paper and in the pretrained model in configs/pointcloud/onet_pretrained.yaml. 
Many thanks.

**Comment by LMescheder** [comment]
Hi @MiZhenxing ,
in the paper, we report all values in terms of 1/10 of the maximal edge length of the object's bounding box (as stated on p. 5 in the paper). Because in the implementation the maximal edge length is 1, there is a factor 10 difference in all distances (stddev, chamfer distance, ...).
I hope that answers your questions.
Best, Lars

**Comment by MiZhenxing** [comment]
Hi @LMescheder ,
Thank you for your kind response. It's very helpful for my experiments.
Best, Zhenxing.
