### ISSUE TITLE
The unit of Chamfer-L1 in the paper

### ISSUE THREAD

**Issue by MiZhenxing** [autonomousvision/occupancy_networks#20]
Hi, sorry to bother you again.
I have run your code on ShapeNet point cloud data and got the evaluation result. However, the 
Chamfer-L1 in the result is several orders of magnitude lower than that in the table 2. So I am wondering if you have multiplied a large factor on the Chamfer-L1 when reporting in the paper, which is also common in other papers using Chamfer Distance.
Best, Zhenxing

**Comment by LMescheder** [comment]
Hi @MiZhenxing,
Chamfer-L1 in the paper is the average of the accuracy and completness score from the evaluator (Please see the supplementary of our paper for a formal definition). The Chamfer the evaluator outputs is the Chamfer-L2 distance. Whereas Chamfer-L1 has unit m, Chamfer-L2 has unit m^2. We chose to report Chamfer-L1 as it is more interpretable: it's unit is distance instead of squared distance.

**Comment by MiZhenxing** [comment]
@LMescheder Thank you very much.

**Comment by LMescheder** [comment]
Fixed in 2fa5496d14ea2f3340865af24dbd06b988e95651.
